# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e7b995fd13e1d77b8ac039616c735a102f77f306386f3625565c68192649889ffd8739f6af6b94b1b6179c15ec9315a62ed83231619cd0b982b6d2b4592d68a

test:
  secret_key_base: 1fb2cec06a0678d4c113957d4bf0e7446050209bea936e85eabeef150f5ef2426eec33c996670bdc12282e5e5c9222b7a68141ee75b8b3ef65834865fc6f9e2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
